--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/ethan/Pictures/wallpapers-master/Landscapes/1490456083719.jpg"

-- Special
background="#0C1031"
foreground="#c2c5c7"
cursor="#c2c5c7"

-- Colors
color0="#0C1031"
color1="#123c84"
color2="#175ea1"
color3="#1c57c4"
color4="#e44871"
color5="#1a98b8"
color6="#20c5df"
color7="#c2c5c7"
color8="#87898b"
color9="#123c84"
color10="#175ea1"
color11="#1c57c4"
color12="#e44871"
color13="#1a98b8"
color14="#20c5df"
color15="#c2c5c7"
