# Shell variables
# Generated by 'wal'
wallpaper='/home/ethan/Pictures/wallpapers-master/Landscapes/1490456083719.jpg'

# Special
background='#0C1031'
foreground='#c2c5c7'
cursor='#c2c5c7'

# Colors
color0='#0C1031'
color1='#123c84'
color2='#175ea1'
color3='#1c57c4'
color4='#e44871'
color5='#1a98b8'
color6='#20c5df'
color7='#c2c5c7'
color8='#87898b'
color9='#123c84'
color10='#175ea1'
color11='#1c57c4'
color12='#e44871'
color13='#1a98b8'
color14='#20c5df'
color15='#c2c5c7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
